[package]
name = "lambda_mountain"
version = "0.0.10"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "Lambda Mountain"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/-"
keywords = ["programming-language","interpreter","compiler"]

[[bin]]
name = "lm"

[dependencies]
im-lists   = { version = "0.4" }

