name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: shopt -s expand_aliases && alias cc='clang' && cargo test --verbose
    - name: Run deploy
      run: shopt -s expand_aliases && alias cc='clang' && make deploy-lite
